name: Build and Test

on:
    workflow_dispatch:

jobs:
    
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
                compiler: [g++, clang]  # Specify compiler versions to test
                cxxstd: [17, 20]  # Specify the language standard to test

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: |
                  cmake -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} \
                        -DCMAKE_CXX_STANDARD=${{ matrix.cxxstd }} \
                        .
                  cmake --build .
                  ctest .
