name: Build and Test

on:
    workflow_dispatch:

jobs:
    
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build And Test
              run: |
                  cmake .
                  cmake --build .
                  ctest -V .
